# Generated by Django 3.1.3 on 2022-09-26 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suscriptor',
            fields=[
                ('IdSuscriptor', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('NumeroDocumento', models.CharField(max_length=50)),
                ('TipoDocumento', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=100)),
                ('Telefono', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('NombreUsuario', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('IdAsociacion', models.AutoField(primary_key=True, serialize=False)),
                ('FechaAlta', models.DateTimeField()),
                ('FechaFin', models.DateTimeField(blank=True)),
                ('MotivoFin', models.CharField(blank=True, max_length=255)),
                ('IdSuscriptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register.suscriptor')),
            ],
        ),
    ]
