# Generated by Django 3.1.3 on 2022-09-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='MotivoFin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
