# Generated by Django 3.1.3 on 2022-09-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0002_auto_20220925_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='FechaFin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
